CREATE DATABASE [JournalTrendDB];
GO
USE [JournalTrendDB];
GO
-- Note: Bỏ qua CREATE USER [admin] vì login không tồn tại trên local
-- Nếu cần, tạo login trước:
-- CREATE LOGIN [admin] WITH PASSWORD = 'your_password';
-- CREATE USER [admin] FOR LOGIN [admin] WITH DEFAULT_SCHEMA=[dbo]
-- ALTER ROLE [db_owner] ADD MEMBER [admin]

/****** Object:  Table [dbo].[ROLE]    Script Date: 7/3/2026 8:46:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLE](
	[RoleID] [uniqueidentifier] NOT NULL,
	[RoleName] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](500) NULL,
 CONSTRAINT [PK_ROLE] PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_ROLE_Name] UNIQUE NONCLUSTERED 
(
	[RoleName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Seed data: 3 roles (academic_user, researcher, admin)
INSERT INTO [dbo].[ROLE] ([RoleID], [RoleName], [Description])
VALUES
    ('00000000-0000-0000-0000-000000000001', 'academic_user', N'Default user with monthly usage limits'),
    ('00000000-0000-0000-0000-000000000002', 'researcher', N'Unlimited access + advanced filters'),
    ('00000000-0000-0000-0000-000000000003', 'admin', N'Full system administration');
GO

/****** Object:  Table [dbo].[USER]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER](
	[UserID] [uniqueidentifier] NOT NULL,
	[RoleID] [uniqueidentifier] NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[PasswordHash] [nvarchar](255) NOT NULL,
	[FullName] [nvarchar](200) NOT NULL,
	[Institution] [nvarchar](300) NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedAt] [datetime2](0) NOT NULL,
	[LastLoginAt] [datetime2](0) NULL,
	[RoleExpiryAt] [datetime2](7) NULL,
	[BackgroundUrl] [nvarchar](500) NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_USER_Email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[V_USER_DETAIL]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- ============================================================
--  VIEWS
-- ============================================================

-- View: Thong tin day du user kem role name
CREATE   VIEW [dbo].[V_USER_DETAIL] AS
SELECT
    u.UserID,
    u.Email,
    u.FullName,
    u.Institution,
    u.IsActive,
    u.CreatedAt,
    u.LastLoginAt,
    r.RoleName,
    r.RoleID
FROM [USER] u
JOIN ROLE r ON u.RoleID = r.RoleID;
GO
/****** Object:  Table [dbo].[RESEARCH_TOPIC]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESEARCH_TOPIC](
	[TopicID] [uniqueidentifier] NOT NULL,
	[FieldID] [uniqueidentifier] NULL,
	[TopicName] [nvarchar](300) NOT NULL,
	[IsTrending] [bit] NOT NULL,
	[TrendScore] [decimal](10, 4) NOT NULL,
	[PaperCount] [int] NOT NULL,
	[UpdatedAt] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_RESEARCH_TOPIC] PRIMARY KEY CLUSTERED 
(
	[TopicID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TOPIC_KEYWORD]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TOPIC_KEYWORD](
	[TopicID] [uniqueidentifier] NOT NULL,
	[KeywordID] [uniqueidentifier] NOT NULL,
	[Weight] [decimal](5, 4) NOT NULL,
 CONSTRAINT [PK_TOPIC_KEYWORD] PRIMARY KEY CLUSTERED 
(
	[TopicID] ASC,
	[KeywordID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RESEARCH_FIELD]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESEARCH_FIELD](
	[FieldID] [uniqueidentifier] NOT NULL,
	[ParentFieldID] [uniqueidentifier] NULL,
	[FieldName] [nvarchar](200) NOT NULL,
	[IsTracked] [bit] NOT NULL,
	[Description] [nvarchar](500) NULL,
 CONSTRAINT [PK_RESEARCH_FIELD] PRIMARY KEY CLUSTERED 
(
	[FieldID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_FIELD_Name] UNIQUE NONCLUSTERED 
(
	[FieldName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[V_TRENDING_TOPICS]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- View: Top trending topics hien tai
CREATE   VIEW [dbo].[V_TRENDING_TOPICS] AS
SELECT
    t.TopicID,
    t.TopicName,
    t.TrendScore,
    t.PaperCount,
    t.UpdatedAt,
    f.FieldName,
    COUNT(tk.KeywordID) AS KeywordCount
FROM RESEARCH_TOPIC t
LEFT JOIN RESEARCH_FIELD f  ON t.FieldID = f.FieldID
LEFT JOIN TOPIC_KEYWORD  tk ON t.TopicID = tk.TopicID
WHERE t.IsTrending = 1
GROUP BY
    t.TopicID, t.TopicName, t.TrendScore,
    t.PaperCount, t.UpdatedAt, f.FieldName;
GO
/****** Object:  Table [dbo].[SYSTEM_CONFIG]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYSTEM_CONFIG](
	[ConfigID] [uniqueidentifier] NOT NULL,
	[ConfigKey] [nvarchar](100) NOT NULL,
	[ConfigValue] [nvarchar](500) NOT NULL,
	[Description] [nvarchar](500) NULL,
	[UpdatedAt] [datetime2](0) NOT NULL,
	[UpdatedBy] [uniqueidentifier] NULL,
 CONSTRAINT [PK_SYSTEM_CONFIG] PRIMARY KEY CLUSTERED 
(
	[ConfigID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_CONFIG_Key] UNIQUE NONCLUSTERED 
(
	[ConfigKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER_USAGE]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_USAGE](
	[UsageID] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[UsageMonth] [char](7) NOT NULL,
	[SearchCount] [int] NOT NULL,
	[ViewCount] [int] NOT NULL,
	[ChartViewCount] [int] NOT NULL,
	[LastUpdated] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_USER_USAGE] PRIMARY KEY CLUSTERED 
(
	[UsageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_USAGE_UserMonth] UNIQUE NONCLUSTERED 
(
	[UserID] ASC,
	[UsageMonth] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[V_ACADEMIC_USAGE_CURRENT]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- View: Usage cua Academic User thang hien tai
CREATE   VIEW [dbo].[V_ACADEMIC_USAGE_CURRENT] AS
SELECT
    u.UserID,
    u.Email,
    u.FullName,
    uu.UsageMonth,
    ISNULL(uu.SearchCount,    0) AS SearchCount,
    ISNULL(uu.ViewCount,      0) AS ViewCount,
    ISNULL(uu.ChartViewCount, 0) AS ChartViewCount,
    (SELECT ConfigValue FROM SYSTEM_CONFIG
     WHERE ConfigKey = 'academic_monthly_search_limit') AS SearchLimit,
    (SELECT ConfigValue FROM SYSTEM_CONFIG
     WHERE ConfigKey = 'academic_monthly_view_limit')   AS ViewLimit,
    (SELECT ConfigValue FROM SYSTEM_CONFIG
     WHERE ConfigKey = 'academic_monthly_chart_limit')  AS ChartLimit
FROM [USER] u
JOIN ROLE r ON u.RoleID = r.RoleID AND r.RoleName = 'academic_user'
LEFT JOIN USER_USAGE uu
    ON u.UserID = uu.UserID
    AND uu.UsageMonth = FORMAT(SYSDATETIME(), 'yyyy-MM');
GO
/****** Object:  Table [dbo].[API_SOURCE]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[API_SOURCE](
	[SourceID] [uniqueidentifier] NOT NULL,
	[SourceName] [nvarchar](100) NOT NULL,
	[BaseURL] [nvarchar](500) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[RateLimitRPM] [int] NULL,
	[LastSyncedAt] [datetime2](0) NULL,
 CONSTRAINT [PK_API_SOURCE] PRIMARY KEY CLUSTERED 
(
	[SourceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_API_SOURCE_Name] UNIQUE NONCLUSTERED 
(
	[SourceName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYNC_LOG]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYNC_LOG](
	[LogID] [uniqueidentifier] NOT NULL,
	[SourceID] [uniqueidentifier] NOT NULL,
	[SyncType] [nvarchar](15) NOT NULL,
	[IsManual] [bit] NOT NULL,
	[Status] [nvarchar](20) NOT NULL,
	[PapersFetched] [int] NULL,
	[PapersInserted] [int] NULL,
	[ErrorMessage] [nvarchar](max) NULL,
	[StartedAt] [datetime2](0) NOT NULL,
	[CompletedAt] [datetime2](0) NULL,
	[PapersUpdated] [int] NULL,
 CONSTRAINT [PK_SYNC_LOG] PRIMARY KEY CLUSTERED 
(
	[LogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  View [dbo].[V_SYNC_HISTORY]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE   VIEW [dbo].[V_SYNC_HISTORY] AS SELECT sl.LogID, sl.StartedAt, sl.CompletedAt, sl.SyncType, sl.IsManual, sl.Status, sl.PapersFetched, sl.PapersInserted, sl.PapersUpdated, sl.ErrorMessage, src.SourceName, DATEDIFF(SECOND, sl.StartedAt, sl.CompletedAt) AS DurationSeconds FROM dbo.SYNC_LOG sl JOIN dbo.API_SOURCE src ON sl.SourceID = src.SourceID;
GO
/****** Object:  Table [dbo].[AUDIT_LOG]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AUDIT_LOG](
	[AuditID] [uniqueidentifier] NOT NULL,
	[AdminID] [uniqueidentifier] NOT NULL,
	[Action] [nvarchar](200) NOT NULL,
	[TargetTable] [nvarchar](100) NULL,
	[TargetID] [nvarchar](100) NULL,
	[OldValue] [nvarchar](max) NULL,
	[NewValue] [nvarchar](max) NULL,
	[IPAddress] [nvarchar](45) NULL,
	[CreatedAt] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_AUDIT_LOG] PRIMARY KEY CLUSTERED 
(
	[AuditID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AUTO_SYNC_KEYWORD]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AUTO_SYNC_KEYWORD](
	[KeywordID] [uniqueidentifier] NOT NULL,
	[Keyword] [nvarchar](500) NOT NULL,
	[IntervalMinutes] [int] NOT NULL,
	[Enabled] [bit] NOT NULL,
	[LastSyncedAt] [datetime2](7) NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[KeywordID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AUTHOR]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AUTHOR](
	[AuthorID] [uniqueidentifier] NOT NULL,
	[SourceID] [uniqueidentifier] NOT NULL,
	[ExternalAuthorID] [nvarchar](200) NULL,
	[FullName] [nvarchar](300) NOT NULL,
	[Affiliation] [nvarchar](500) NULL,
	[HIndex] [int] NULL,
	[TotalCitations] [int] NULL,
 CONSTRAINT [PK_AUTHOR] PRIMARY KEY CLUSTERED 
(
	[AuthorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BOOKMARK]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BOOKMARK](
	[BookmarkID] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[PaperID] [uniqueidentifier] NULL,
	[KeywordID] [uniqueidentifier] NULL,
	[Notes] [nvarchar](500) NULL,
	[CreatedAt] [datetime2](0) NOT NULL,
	[CollectionID] [uniqueidentifier] NULL,
	[LastNotifiedMilestone] [int] NOT NULL,
 CONSTRAINT [PK_BOOKMARK] PRIMARY KEY CLUSTERED 
(
	[BookmarkID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BOOKMARK_COLLECTION]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BOOKMARK_COLLECTION](
	[CollectionID] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
	[Description] [nvarchar](500) NULL,
	[CreatedAt] [datetime2](0) NOT NULL,
	[UpdatedAt] [datetime2](0) NOT NULL,
	[LastNotifiedMilestone] [int] NOT NULL,
 CONSTRAINT [PK_BOOKMARK_COLLECTION] PRIMARY KEY CLUSTERED 
(
	[CollectionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_BC_User_Name] UNIQUE NONCLUSTERED 
(
	[UserID] ASC,
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DASHBOARD_WIDGET]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DASHBOARD_WIDGET](
	[WidgetID] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[WidgetType] [nvarchar](30) NOT NULL,
	[Title] [nvarchar](200) NOT NULL,
	[Config] [nvarchar](max) NULL,
	[PositionX] [int] NOT NULL,
	[PositionY] [int] NOT NULL,
	[Width] [int] NOT NULL,
	[Height] [int] NOT NULL,
	[CreatedAt] [datetime2](0) NOT NULL,
	[UpdatedAt] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_DASHBOARD_WIDGET] PRIMARY KEY CLUSTERED 
(
	[WidgetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FOLLOW]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FOLLOW](
	[FollowID] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[JournalID] [uniqueidentifier] NULL,
	[TopicID] [uniqueidentifier] NULL,
	[KeywordID] [uniqueidentifier] NULL,
	[NotifyEnabled] [bit] NOT NULL,
	[CreatedAt] [datetime2](0) NOT NULL,
	[AuthorID] [uniqueidentifier] NULL,
 CONSTRAINT [PK_FOLLOW] PRIMARY KEY CLUSTERED 
(
	[FollowID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOURNAL]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOURNAL](
	[JournalID] [uniqueidentifier] NOT NULL,
	[SourceID] [uniqueidentifier] NOT NULL,
	[FieldID] [uniqueidentifier] NULL,
	[JournalName] [nvarchar](500) NOT NULL,
	[ISSN] [nvarchar](20) NULL,
	[Publisher] [nvarchar](300) NULL,
	[ImpactFactor] [decimal](8, 3) NULL,
	[Quartile] [char](2) NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_JOURNAL] PRIMARY KEY CLUSTERED 
(
	[JournalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KEYWORD]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KEYWORD](
	[KeywordID] [uniqueidentifier] NOT NULL,
	[FieldID] [uniqueidentifier] NULL,
	[KeywordText] [nvarchar](300) NOT NULL,
	[NormalizedText] [nvarchar](300) NOT NULL,
	[PaperCount] [int] NOT NULL,
 CONSTRAINT [PK_KEYWORD] PRIMARY KEY CLUSTERED 
(
	[KeywordID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_KEYWORD_Normalized] UNIQUE NONCLUSTERED 
(
	[NormalizedText] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTIFICATION]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATION](
	[NotifID] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[Type] [nvarchar](20) NOT NULL,
	[Title] [nvarchar](300) NOT NULL,
	[Message] [nvarchar](max) NULL,
	[RelatedPaperID] [uniqueidentifier] NULL,
	[RelatedJournalID] [uniqueidentifier] NULL,
	[RelatedTopicID] [uniqueidentifier] NULL,
	[RelatedKeywordID] [uniqueidentifier] NULL,
	[IsRead] [bit] NOT NULL,
	[CreatedAt] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_NOTIFICATION] PRIMARY KEY CLUSTERED 
(
	[NotifID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAPER_AUTHOR]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAPER_AUTHOR](
	[PaperID] [uniqueidentifier] NOT NULL,
	[AuthorID] [uniqueidentifier] NOT NULL,
	[AuthorOrder] [smallint] NOT NULL,
	[IsCorresponding] [bit] NOT NULL,
 CONSTRAINT [PK_PAPER_AUTHOR] PRIMARY KEY CLUSTERED 
(
	[PaperID] ASC,
	[AuthorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAPER_KEYWORD]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAPER_KEYWORD](
	[PaperID] [uniqueidentifier] NOT NULL,
	[KeywordID] [uniqueidentifier] NOT NULL,
	[RelevanceScore] [decimal](5, 4) NULL,
 CONSTRAINT [PK_PAPER_KEYWORD] PRIMARY KEY CLUSTERED 
(
	[PaperID] ASC,
	[KeywordID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PDF_REQUEST]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PDF_REQUEST](
	[RequestID] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[PaperID] [uniqueidentifier] NOT NULL,
	[Status] [nvarchar](20) NOT NULL,
	[UserMessage] [nvarchar](1000) NULL,
	[AdminNote] [nvarchar](1000) NULL,
	[RequestedAt] [datetime2](7) NOT NULL,
	[ResolvedAt] [datetime2](7) NULL,
	[ResolvedByAdminID] [uniqueidentifier] NULL,
 CONSTRAINT [PK_PDF_REQUEST] PRIMARY KEY CLUSTERED 
(
	[RequestID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PUBLICATION_TREND]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUBLICATION_TREND](
	[TrendID] [uniqueidentifier] NOT NULL,
	[PeriodType] [nvarchar](10) NOT NULL,
	[PeriodValue] [nvarchar](15) NOT NULL,
	[TrendTarget] [nvarchar](10) NOT NULL,
	[TargetID] [uniqueidentifier] NOT NULL,
	[PaperCount] [int] NOT NULL,
	[CitationCount] [int] NOT NULL,
	[GrowthRate] [decimal](10, 4) NULL,
	[CalculatedAt] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_PUBLICATION_TREND] PRIMARY KEY CLUSTERED 
(
	[TrendID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_TREND_Period] UNIQUE NONCLUSTERED 
(
	[TrendTarget] ASC,
	[TargetID] ASC,
	[PeriodType] ASC,
	[PeriodValue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REPORT]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPORT](
	[ReportID] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[FieldID] [uniqueidentifier] NULL,
	[ReportName] [nvarchar](300) NOT NULL,
	[PeriodStart] [date] NOT NULL,
	[PeriodEnd] [date] NOT NULL,
	[Status] [nvarchar](20) NOT NULL,
	[Format] [nvarchar](5) NOT NULL,
	[FileURL] [nvarchar](1000) NULL,
	[CreatedAt] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_REPORT] PRIMARY KEY CLUSTERED 
(
	[ReportID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RESEARCH_PAPER]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESEARCH_PAPER](
	[PaperID] [uniqueidentifier] NOT NULL,
	[SourceID] [uniqueidentifier] NOT NULL,
	[JournalID] [uniqueidentifier] NULL,
	[FieldID] [uniqueidentifier] NULL,
	[Title] [nvarchar](1000) NOT NULL,
	[Abstract] [nvarchar](max) NULL,
	[DOI] [nvarchar](200) NULL,
	[PubDate] [date] NULL,
	[PubYear] [smallint] NULL,
	[CitationCount] [int] NOT NULL,
	[IsOpenAccess] [bit] NOT NULL,
	[CreatedAt] [datetime2](0) NOT NULL,
	[PdfUrl] [nvarchar](500) NULL,
 CONSTRAINT [PK_RESEARCH_PAPER] PRIMARY KEY CLUSTERED 
(
	[PaperID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SEARCH_KEYWORD]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SEARCH_KEYWORD](
	[SearchKeywordID] [uniqueidentifier] NOT NULL,
	[KeywordText] [nvarchar](500) NOT NULL,
	[NormalizedText] [nvarchar](500) NOT NULL,
	[SearchCount] [int] NOT NULL,
	[LastSearchedAt] [datetime2](7) NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SearchKeywordID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[NormalizedText] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRENDING_TOPIC]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRENDING_TOPIC](
	[TrendingTopicID] [uniqueidentifier] NOT NULL,
	[TopicName] [nvarchar](300) NOT NULL,
	[PaperCount] [int] NOT NULL,
	[Source] [nvarchar](50) NOT NULL,
	[DisplayOrder] [int] NOT NULL,
	[UpdatedAt] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_TRENDING_TOPIC] PRIMARY KEY CLUSTERED 
(
	[TrendingTopicID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER_SEARCH_HISTORY]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_SEARCH_HISTORY](
	[SearchHistoryID] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[SearchText] [nvarchar](500) NOT NULL,
	[SearchType] [nvarchar](20) NOT NULL,
	[SearchedAt] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_USER_SEARCH_HISTORY] PRIMARY KEY CLUSTERED 
(
	[SearchHistoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER_SESSION]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_SESSION](
	[SessionID] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[TokenHash] [nvarchar](500) NOT NULL,
	[ExpiresAt] [datetime2](0) NOT NULL,
	[CreatedAt] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_USER_SESSION] PRIMARY KEY CLUSTERED 
(
	[SessionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VERIFICATION_TOKEN]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VERIFICATION_TOKEN](
	[TokenID] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[Token] [nvarchar](255) NOT NULL,
	[TokenType] [nvarchar](20) NOT NULL,
	[ExpiresAt] [datetime2](0) NOT NULL,
	[CreatedAt] [datetime2](0) NOT NULL,
	[IsUsed] [bit] NOT NULL,
 CONSTRAINT [PK_VERIFICATION_TOKEN] PRIMARY KEY CLUSTERED 
(
	[TokenID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_VT_Token] UNIQUE NONCLUSTERED 
(
	[Token] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_AUDIT_AdminID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_AUDIT_AdminID] ON [dbo].[AUDIT_LOG]
(
	[AdminID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_AUDIT_CreatedAt]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_AUDIT_CreatedAt] ON [dbo].[AUDIT_LOG]
(
	[CreatedAt] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UK_AUTHOR_External]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_AUTHOR_External] ON [dbo].[AUTHOR]
(
	[SourceID] ASC,
	[ExternalAuthorID] ASC
)
WHERE ([ExternalAuthorID] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_BOOKMARK_CollectionID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_BOOKMARK_CollectionID] ON [dbo].[BOOKMARK]
(
	[CollectionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_BOOKMARK_UserID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_BOOKMARK_UserID] ON [dbo].[BOOKMARK]
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UK_BOOKMARK_Keyword]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_BOOKMARK_Keyword] ON [dbo].[BOOKMARK]
(
	[UserID] ASC,
	[KeywordID] ASC
)
WHERE ([KeywordID] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UK_BOOKMARK_Paper]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_BOOKMARK_Paper] ON [dbo].[BOOKMARK]
(
	[UserID] ASC,
	[PaperID] ASC
)
WHERE ([PaperID] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_FOLLOW_UserID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_FOLLOW_UserID] ON [dbo].[FOLLOW]
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UK_FOLLOW_Journal]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_FOLLOW_Journal] ON [dbo].[FOLLOW]
(
	[UserID] ASC,
	[JournalID] ASC
)
WHERE ([JournalID] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UK_FOLLOW_Keyword]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_FOLLOW_Keyword] ON [dbo].[FOLLOW]
(
	[UserID] ASC,
	[KeywordID] ASC
)
WHERE ([KeywordID] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UK_FOLLOW_Topic]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_FOLLOW_Topic] ON [dbo].[FOLLOW]
(
	[UserID] ASC,
	[TopicID] ASC
)
WHERE ([TopicID] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_JOURNAL_FieldID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_JOURNAL_FieldID] ON [dbo].[JOURNAL]
(
	[FieldID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_JOURNAL_SourceID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_JOURNAL_SourceID] ON [dbo].[JOURNAL]
(
	[SourceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UK_JOURNAL_ISSN]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_JOURNAL_ISSN] ON [dbo].[JOURNAL]
(
	[ISSN] ASC
)
WHERE ([ISSN] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_KEYWORD_FieldID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_KEYWORD_FieldID] ON [dbo].[KEYWORD]
(
	[FieldID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_KEYWORD_Normalized]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_KEYWORD_Normalized] ON [dbo].[KEYWORD]
(
	[NormalizedText] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_NOTIF_CreatedAt]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_NOTIF_CreatedAt] ON [dbo].[NOTIFICATION]
(
	[CreatedAt] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_NOTIF_UserUnread]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_NOTIF_UserUnread] ON [dbo].[NOTIFICATION]
(
	[UserID] ASC,
	[IsRead] ASC,
	[CreatedAt] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_PDF_REQUEST_StatusRequestedAt]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_PDF_REQUEST_StatusRequestedAt] ON [dbo].[PDF_REQUEST]
(
	[Status] ASC,
	[RequestedAt] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UX_PDF_REQUEST_UserPaperPending]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_PDF_REQUEST_UserPaperPending] ON [dbo].[PDF_REQUEST]
(
	[UserID] ASC,
	[PaperID] ASC
)
WHERE ([Status]='pending')
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_TREND_Full]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_TREND_Full] ON [dbo].[PUBLICATION_TREND]
(
	[TrendTarget] ASC,
	[TargetID] ASC,
	[PeriodType] ASC,
	[PeriodValue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_TREND_Period]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_TREND_Period] ON [dbo].[PUBLICATION_TREND]
(
	[PeriodType] ASC,
	[PeriodValue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_TREND_Target]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_TREND_Target] ON [dbo].[PUBLICATION_TREND]
(
	[TrendTarget] ASC,
	[TargetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_REPORT_Status]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_REPORT_Status] ON [dbo].[REPORT]
(
	[Status] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_REPORT_UserID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_REPORT_UserID] ON [dbo].[REPORT]
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_FIELD_ParentID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_FIELD_ParentID] ON [dbo].[RESEARCH_FIELD]
(
	[ParentFieldID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_PAPER_CITATIONS]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IDX_PAPER_CITATIONS] ON [dbo].[RESEARCH_PAPER]
(
	[CitationCount] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_PAPER_CREATEDAT]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IDX_PAPER_CREATEDAT] ON [dbo].[RESEARCH_PAPER]
(
	[CreatedAt] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_PAPER_PUBYEAR]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IDX_PAPER_PUBYEAR] ON [dbo].[RESEARCH_PAPER]
(
	[PubYear] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
-- Skipped: IDX_PAPER_TITLE on Title (nvarchar(1000) exceeds 1700-byte key limit)
-- CREATE NONCLUSTERED INDEX [IDX_PAPER_TITLE] ON [dbo].[RESEARCH_PAPER] ([Title] ASC)
-- GO
/****** Object:  Index [IX_PAPER_CreatedAt]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_PAPER_CreatedAt] ON [dbo].[RESEARCH_PAPER]
(
	[CreatedAt] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_PAPER_FieldID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_PAPER_FieldID] ON [dbo].[RESEARCH_PAPER]
(
	[FieldID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_PAPER_JournalID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_PAPER_JournalID] ON [dbo].[RESEARCH_PAPER]
(
	[JournalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_PAPER_PubYear]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_PAPER_PubYear] ON [dbo].[RESEARCH_PAPER]
(
	[PubYear] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UK_PAPER_DOI]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_PAPER_DOI] ON [dbo].[RESEARCH_PAPER]
(
	[DOI] ASC
)
WHERE ([DOI] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TOPIC_FieldID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_TOPIC_FieldID] ON [dbo].[RESEARCH_TOPIC]
(
	[FieldID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TOPIC_IsTrending]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_TOPIC_IsTrending] ON [dbo].[RESEARCH_TOPIC]
(
	[IsTrending] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TOPIC_TrendScore]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_TOPIC_TrendScore] ON [dbo].[RESEARCH_TOPIC]
(
	[TrendScore] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_SYNC_SourceID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_SYNC_SourceID] ON [dbo].[SYNC_LOG]
(
	[SourceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_SYNC_StartedAt]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_SYNC_StartedAt] ON [dbo].[SYNC_LOG]
(
	[StartedAt] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TRENDING_TOPIC_DisplayOrder]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_TRENDING_TOPIC_DisplayOrder] ON [dbo].[TRENDING_TOPIC]
(
	[DisplayOrder] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_USER_IsActive]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_USER_IsActive] ON [dbo].[USER]
(
	[IsActive] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_USER_RoleID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_USER_RoleID] ON [dbo].[USER]
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_USH_UserID_SearchedAt]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_USH_UserID_SearchedAt] ON [dbo].[USER_SEARCH_HISTORY]
(
	[UserID] ASC,
	[SearchedAt] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_SESSION_ExpiresAt]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_SESSION_ExpiresAt] ON [dbo].[USER_SESSION]
(
	[ExpiresAt] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_SESSION_UserID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_SESSION_UserID] ON [dbo].[USER_SESSION]
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_USAGE_UserMonth]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_USAGE_UserMonth] ON [dbo].[USER_USAGE]
(
	[UserID] ASC,
	[UsageMonth] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_VT_ExpiresAt]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_VT_ExpiresAt] ON [dbo].[VERIFICATION_TOKEN]
(
	[ExpiresAt] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_VT_Token]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_VT_Token] ON [dbo].[VERIFICATION_TOKEN]
(
	[Token] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_VT_UserID]    Script Date: 7/3/2026 8:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_VT_UserID] ON [dbo].[VERIFICATION_TOKEN]
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[API_SOURCE] ADD  DEFAULT (newid()) FOR [SourceID]
GO
ALTER TABLE [dbo].[API_SOURCE] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[AUDIT_LOG] ADD  DEFAULT (newid()) FOR [AuditID]
GO
ALTER TABLE [dbo].[AUDIT_LOG] ADD  DEFAULT (sysdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[AUTO_SYNC_KEYWORD] ADD  DEFAULT ((60)) FOR [IntervalMinutes]
GO
ALTER TABLE [dbo].[AUTO_SYNC_KEYWORD] ADD  DEFAULT ((1)) FOR [Enabled]
GO
ALTER TABLE [dbo].[AUTO_SYNC_KEYWORD] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[AUTHOR] ADD  DEFAULT (newid()) FOR [AuthorID]
GO
ALTER TABLE [dbo].[AUTHOR] ADD  DEFAULT ((0)) FOR [HIndex]
GO
ALTER TABLE [dbo].[AUTHOR] ADD  DEFAULT ((0)) FOR [TotalCitations]
GO
ALTER TABLE [dbo].[BOOKMARK] ADD  DEFAULT (newid()) FOR [BookmarkID]
GO
ALTER TABLE [dbo].[BOOKMARK] ADD  DEFAULT (sysdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[BOOKMARK] ADD  DEFAULT ((0)) FOR [LastNotifiedMilestone]
GO
ALTER TABLE [dbo].[BOOKMARK_COLLECTION] ADD  DEFAULT (newid()) FOR [CollectionID]
GO
ALTER TABLE [dbo].[BOOKMARK_COLLECTION] ADD  DEFAULT (sysdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[BOOKMARK_COLLECTION] ADD  DEFAULT (sysdatetime()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[BOOKMARK_COLLECTION] ADD  DEFAULT ((0)) FOR [LastNotifiedMilestone]
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET] ADD  DEFAULT (newid()) FOR [WidgetID]
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET] ADD  DEFAULT ((0)) FOR [PositionX]
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET] ADD  DEFAULT ((0)) FOR [PositionY]
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET] ADD  DEFAULT ((4)) FOR [Width]
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET] ADD  DEFAULT ((3)) FOR [Height]
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET] ADD  DEFAULT (sysdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET] ADD  DEFAULT (sysdatetime()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[FOLLOW] ADD  DEFAULT (newid()) FOR [FollowID]
GO
ALTER TABLE [dbo].[FOLLOW] ADD  DEFAULT ((1)) FOR [NotifyEnabled]
GO
ALTER TABLE [dbo].[FOLLOW] ADD  DEFAULT (sysdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[JOURNAL] ADD  DEFAULT (newid()) FOR [JournalID]
GO
ALTER TABLE [dbo].[JOURNAL] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[KEYWORD] ADD  DEFAULT (newid()) FOR [KeywordID]
GO
ALTER TABLE [dbo].[KEYWORD] ADD  DEFAULT ((0)) FOR [PaperCount]
GO
ALTER TABLE [dbo].[NOTIFICATION] ADD  DEFAULT (newid()) FOR [NotifID]
GO
ALTER TABLE [dbo].[NOTIFICATION] ADD  DEFAULT ((0)) FOR [IsRead]
GO
ALTER TABLE [dbo].[NOTIFICATION] ADD  DEFAULT (sysdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[PAPER_AUTHOR] ADD  DEFAULT ((1)) FOR [AuthorOrder]
GO
ALTER TABLE [dbo].[PAPER_AUTHOR] ADD  DEFAULT ((0)) FOR [IsCorresponding]
GO
ALTER TABLE [dbo].[PDF_REQUEST] ADD  DEFAULT (newid()) FOR [RequestID]
GO
ALTER TABLE [dbo].[PDF_REQUEST] ADD  DEFAULT ('pending') FOR [Status]
GO
ALTER TABLE [dbo].[PDF_REQUEST] ADD  DEFAULT (sysdatetime()) FOR [RequestedAt]
GO
ALTER TABLE [dbo].[PUBLICATION_TREND] ADD  DEFAULT (newid()) FOR [TrendID]
GO
ALTER TABLE [dbo].[PUBLICATION_TREND] ADD  DEFAULT ((0)) FOR [PaperCount]
GO
ALTER TABLE [dbo].[PUBLICATION_TREND] ADD  DEFAULT ((0)) FOR [CitationCount]
GO
ALTER TABLE [dbo].[PUBLICATION_TREND] ADD  DEFAULT (sysdatetime()) FOR [CalculatedAt]
GO
ALTER TABLE [dbo].[REPORT] ADD  DEFAULT (newid()) FOR [ReportID]
GO
ALTER TABLE [dbo].[REPORT] ADD  DEFAULT ('generating') FOR [Status]
GO
ALTER TABLE [dbo].[REPORT] ADD  DEFAULT ('pdf') FOR [Format]
GO
ALTER TABLE [dbo].[REPORT] ADD  DEFAULT (sysdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[RESEARCH_FIELD] ADD  DEFAULT (newid()) FOR [FieldID]
GO
ALTER TABLE [dbo].[RESEARCH_FIELD] ADD  DEFAULT ((1)) FOR [IsTracked]
GO
ALTER TABLE [dbo].[RESEARCH_PAPER] ADD  DEFAULT (newid()) FOR [PaperID]
GO
ALTER TABLE [dbo].[RESEARCH_PAPER] ADD  DEFAULT ((0)) FOR [CitationCount]
GO
ALTER TABLE [dbo].[RESEARCH_PAPER] ADD  DEFAULT ((0)) FOR [IsOpenAccess]
GO
ALTER TABLE [dbo].[RESEARCH_PAPER] ADD  DEFAULT (sysdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[RESEARCH_TOPIC] ADD  DEFAULT (newid()) FOR [TopicID]
GO
ALTER TABLE [dbo].[RESEARCH_TOPIC] ADD  DEFAULT ((0)) FOR [IsTrending]
GO
ALTER TABLE [dbo].[RESEARCH_TOPIC] ADD  DEFAULT ((0)) FOR [TrendScore]
GO
ALTER TABLE [dbo].[RESEARCH_TOPIC] ADD  DEFAULT ((0)) FOR [PaperCount]
GO
ALTER TABLE [dbo].[RESEARCH_TOPIC] ADD  DEFAULT (sysdatetime()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[ROLE] ADD  DEFAULT (newid()) FOR [RoleID]
GO
ALTER TABLE [dbo].[SEARCH_KEYWORD] ADD  DEFAULT (newid()) FOR [SearchKeywordID]
GO
ALTER TABLE [dbo].[SEARCH_KEYWORD] ADD  DEFAULT ((1)) FOR [SearchCount]
GO
ALTER TABLE [dbo].[SEARCH_KEYWORD] ADD  DEFAULT (getdate()) FOR [LastSearchedAt]
GO
ALTER TABLE [dbo].[SEARCH_KEYWORD] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[SYNC_LOG] ADD  DEFAULT (newid()) FOR [LogID]
GO
ALTER TABLE [dbo].[SYNC_LOG] ADD  DEFAULT ((0)) FOR [IsManual]
GO
ALTER TABLE [dbo].[SYNC_LOG] ADD  DEFAULT ('running') FOR [Status]
GO
ALTER TABLE [dbo].[SYNC_LOG] ADD  DEFAULT ((0)) FOR [PapersFetched]
GO
ALTER TABLE [dbo].[SYNC_LOG] ADD  DEFAULT ((0)) FOR [PapersInserted]
GO
ALTER TABLE [dbo].[SYNC_LOG] ADD  DEFAULT (sysdatetime()) FOR [StartedAt]
GO
ALTER TABLE [dbo].[SYNC_LOG] ADD  CONSTRAINT [DF_SYNC_LOG_PapersUpdated]  DEFAULT ((0)) FOR [PapersUpdated]
GO
ALTER TABLE [dbo].[SYSTEM_CONFIG] ADD  DEFAULT (newid()) FOR [ConfigID]
GO
ALTER TABLE [dbo].[SYSTEM_CONFIG] ADD  DEFAULT (sysdatetime()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[TOPIC_KEYWORD] ADD  DEFAULT ((1.0)) FOR [Weight]
GO
ALTER TABLE [dbo].[TRENDING_TOPIC] ADD  DEFAULT (newid()) FOR [TrendingTopicID]
GO
ALTER TABLE [dbo].[TRENDING_TOPIC] ADD  DEFAULT ((0)) FOR [PaperCount]
GO
ALTER TABLE [dbo].[TRENDING_TOPIC] ADD  DEFAULT ('openalex') FOR [Source]
GO
ALTER TABLE [dbo].[TRENDING_TOPIC] ADD  DEFAULT ((0)) FOR [DisplayOrder]
GO
ALTER TABLE [dbo].[TRENDING_TOPIC] ADD  DEFAULT (sysutcdatetime()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[USER] ADD  DEFAULT (newid()) FOR [UserID]
GO
ALTER TABLE [dbo].[USER] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[USER] ADD  DEFAULT (sysdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[USER_SEARCH_HISTORY] ADD  DEFAULT (newid()) FOR [SearchHistoryID]
GO
ALTER TABLE [dbo].[USER_SEARCH_HISTORY] ADD  DEFAULT (sysutcdatetime()) FOR [SearchedAt]
GO
ALTER TABLE [dbo].[USER_SESSION] ADD  DEFAULT (newid()) FOR [SessionID]
GO
ALTER TABLE [dbo].[USER_SESSION] ADD  DEFAULT (sysdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[USER_USAGE] ADD  DEFAULT (newid()) FOR [UsageID]
GO
ALTER TABLE [dbo].[USER_USAGE] ADD  DEFAULT ((0)) FOR [SearchCount]
GO
ALTER TABLE [dbo].[USER_USAGE] ADD  DEFAULT ((0)) FOR [ViewCount]
GO
ALTER TABLE [dbo].[USER_USAGE] ADD  DEFAULT ((0)) FOR [ChartViewCount]
GO
ALTER TABLE [dbo].[USER_USAGE] ADD  DEFAULT (sysdatetime()) FOR [LastUpdated]
GO
ALTER TABLE [dbo].[VERIFICATION_TOKEN] ADD  DEFAULT (newid()) FOR [TokenID]
GO
ALTER TABLE [dbo].[VERIFICATION_TOKEN] ADD  DEFAULT (sysdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[VERIFICATION_TOKEN] ADD  DEFAULT ((0)) FOR [IsUsed]
GO
ALTER TABLE [dbo].[AUDIT_LOG]  WITH CHECK ADD  CONSTRAINT [FK_AUDIT_Admin] FOREIGN KEY([AdminID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[AUDIT_LOG] CHECK CONSTRAINT [FK_AUDIT_Admin]
GO
ALTER TABLE [dbo].[AUTHOR]  WITH CHECK ADD  CONSTRAINT [FK_AUTHOR_Source] FOREIGN KEY([SourceID])
REFERENCES [dbo].[API_SOURCE] ([SourceID])
GO
ALTER TABLE [dbo].[AUTHOR] CHECK CONSTRAINT [FK_AUTHOR_Source]
GO
ALTER TABLE [dbo].[BOOKMARK]  WITH CHECK ADD  CONSTRAINT [FK_BM_Keyword] FOREIGN KEY([KeywordID])
REFERENCES [dbo].[KEYWORD] ([KeywordID])
GO
ALTER TABLE [dbo].[BOOKMARK] CHECK CONSTRAINT [FK_BM_Keyword]
GO
ALTER TABLE [dbo].[BOOKMARK]  WITH CHECK ADD  CONSTRAINT [FK_BM_Paper] FOREIGN KEY([PaperID])
REFERENCES [dbo].[RESEARCH_PAPER] ([PaperID])
GO
ALTER TABLE [dbo].[BOOKMARK] CHECK CONSTRAINT [FK_BM_Paper]
GO
ALTER TABLE [dbo].[BOOKMARK]  WITH CHECK ADD  CONSTRAINT [FK_BM_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[BOOKMARK] CHECK CONSTRAINT [FK_BM_User]
GO
ALTER TABLE [dbo].[BOOKMARK_COLLECTION]  WITH CHECK ADD  CONSTRAINT [FK_BC_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[BOOKMARK_COLLECTION] CHECK CONSTRAINT [FK_BC_User]
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET]  WITH CHECK ADD  CONSTRAINT [FK_DW_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET] CHECK CONSTRAINT [FK_DW_User]
GO
ALTER TABLE [dbo].[FOLLOW]  WITH CHECK ADD  CONSTRAINT [FK_FOLLOW_Author] FOREIGN KEY([AuthorID])
REFERENCES [dbo].[AUTHOR] ([AuthorID])
GO
ALTER TABLE [dbo].[FOLLOW] CHECK CONSTRAINT [FK_FOLLOW_Author]
GO
ALTER TABLE [dbo].[FOLLOW]  WITH CHECK ADD  CONSTRAINT [FK_FOLLOW_Journal] FOREIGN KEY([JournalID])
REFERENCES [dbo].[JOURNAL] ([JournalID])
GO
ALTER TABLE [dbo].[FOLLOW] CHECK CONSTRAINT [FK_FOLLOW_Journal]
GO
ALTER TABLE [dbo].[FOLLOW]  WITH CHECK ADD  CONSTRAINT [FK_FOLLOW_Keyword] FOREIGN KEY([KeywordID])
REFERENCES [dbo].[KEYWORD] ([KeywordID])
GO
ALTER TABLE [dbo].[FOLLOW] CHECK CONSTRAINT [FK_FOLLOW_Keyword]
GO
ALTER TABLE [dbo].[FOLLOW]  WITH CHECK ADD  CONSTRAINT [FK_FOLLOW_Topic] FOREIGN KEY([TopicID])
REFERENCES [dbo].[RESEARCH_TOPIC] ([TopicID])
GO
ALTER TABLE [dbo].[FOLLOW] CHECK CONSTRAINT [FK_FOLLOW_Topic]
GO
ALTER TABLE [dbo].[FOLLOW]  WITH CHECK ADD  CONSTRAINT [FK_FOLLOW_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[FOLLOW] CHECK CONSTRAINT [FK_FOLLOW_User]
GO
ALTER TABLE [dbo].[JOURNAL]  WITH CHECK ADD  CONSTRAINT [FK_JOURNAL_Field] FOREIGN KEY([FieldID])
REFERENCES [dbo].[RESEARCH_FIELD] ([FieldID])
GO
ALTER TABLE [dbo].[JOURNAL] CHECK CONSTRAINT [FK_JOURNAL_Field]
GO
ALTER TABLE [dbo].[JOURNAL]  WITH CHECK ADD  CONSTRAINT [FK_JOURNAL_Source] FOREIGN KEY([SourceID])
REFERENCES [dbo].[API_SOURCE] ([SourceID])
GO
ALTER TABLE [dbo].[JOURNAL] CHECK CONSTRAINT [FK_JOURNAL_Source]
GO
ALTER TABLE [dbo].[KEYWORD]  WITH CHECK ADD  CONSTRAINT [FK_KEYWORD_Field] FOREIGN KEY([FieldID])
REFERENCES [dbo].[RESEARCH_FIELD] ([FieldID])
GO
ALTER TABLE [dbo].[KEYWORD] CHECK CONSTRAINT [FK_KEYWORD_Field]
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_NOTIF_Journal] FOREIGN KEY([RelatedJournalID])
REFERENCES [dbo].[JOURNAL] ([JournalID])
GO
ALTER TABLE [dbo].[NOTIFICATION] CHECK CONSTRAINT [FK_NOTIF_Journal]
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_NOTIF_Keyword] FOREIGN KEY([RelatedKeywordID])
REFERENCES [dbo].[KEYWORD] ([KeywordID])
GO
ALTER TABLE [dbo].[NOTIFICATION] CHECK CONSTRAINT [FK_NOTIF_Keyword]
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_NOTIF_Paper] FOREIGN KEY([RelatedPaperID])
REFERENCES [dbo].[RESEARCH_PAPER] ([PaperID])
GO
ALTER TABLE [dbo].[NOTIFICATION] CHECK CONSTRAINT [FK_NOTIF_Paper]
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_NOTIF_Topic] FOREIGN KEY([RelatedTopicID])
REFERENCES [dbo].[RESEARCH_TOPIC] ([TopicID])
GO
ALTER TABLE [dbo].[NOTIFICATION] CHECK CONSTRAINT [FK_NOTIF_Topic]
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_NOTIF_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[NOTIFICATION] CHECK CONSTRAINT [FK_NOTIF_User]
GO
ALTER TABLE [dbo].[PAPER_AUTHOR]  WITH CHECK ADD  CONSTRAINT [FK_PA_Author] FOREIGN KEY([AuthorID])
REFERENCES [dbo].[AUTHOR] ([AuthorID])
GO
ALTER TABLE [dbo].[PAPER_AUTHOR] CHECK CONSTRAINT [FK_PA_Author]
GO
ALTER TABLE [dbo].[PAPER_AUTHOR]  WITH CHECK ADD  CONSTRAINT [FK_PA_Paper] FOREIGN KEY([PaperID])
REFERENCES [dbo].[RESEARCH_PAPER] ([PaperID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PAPER_AUTHOR] CHECK CONSTRAINT [FK_PA_Paper]
GO
ALTER TABLE [dbo].[PAPER_KEYWORD]  WITH CHECK ADD  CONSTRAINT [FK_PK_Keyword] FOREIGN KEY([KeywordID])
REFERENCES [dbo].[KEYWORD] ([KeywordID])
GO
ALTER TABLE [dbo].[PAPER_KEYWORD] CHECK CONSTRAINT [FK_PK_Keyword]
GO
ALTER TABLE [dbo].[PAPER_KEYWORD]  WITH CHECK ADD  CONSTRAINT [FK_PK_Paper] FOREIGN KEY([PaperID])
REFERENCES [dbo].[RESEARCH_PAPER] ([PaperID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PAPER_KEYWORD] CHECK CONSTRAINT [FK_PK_Paper]
GO
ALTER TABLE [dbo].[PDF_REQUEST]  WITH CHECK ADD  CONSTRAINT [FK_PDF_REQUEST_Admin] FOREIGN KEY([ResolvedByAdminID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[PDF_REQUEST] CHECK CONSTRAINT [FK_PDF_REQUEST_Admin]
GO
ALTER TABLE [dbo].[PDF_REQUEST]  WITH CHECK ADD  CONSTRAINT [FK_PDF_REQUEST_Paper] FOREIGN KEY([PaperID])
REFERENCES [dbo].[RESEARCH_PAPER] ([PaperID])
GO
ALTER TABLE [dbo].[PDF_REQUEST] CHECK CONSTRAINT [FK_PDF_REQUEST_Paper]
GO
ALTER TABLE [dbo].[PDF_REQUEST]  WITH CHECK ADD  CONSTRAINT [FK_PDF_REQUEST_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[PDF_REQUEST] CHECK CONSTRAINT [FK_PDF_REQUEST_User]
GO
ALTER TABLE [dbo].[REPORT]  WITH CHECK ADD  CONSTRAINT [FK_REPORT_Field] FOREIGN KEY([FieldID])
REFERENCES [dbo].[RESEARCH_FIELD] ([FieldID])
GO
ALTER TABLE [dbo].[REPORT] CHECK CONSTRAINT [FK_REPORT_Field]
GO
ALTER TABLE [dbo].[REPORT]  WITH CHECK ADD  CONSTRAINT [FK_REPORT_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[REPORT] CHECK CONSTRAINT [FK_REPORT_User]
GO
ALTER TABLE [dbo].[RESEARCH_FIELD]  WITH CHECK ADD  CONSTRAINT [FK_FIELD_Parent] FOREIGN KEY([ParentFieldID])
REFERENCES [dbo].[RESEARCH_FIELD] ([FieldID])
GO
ALTER TABLE [dbo].[RESEARCH_FIELD] CHECK CONSTRAINT [FK_FIELD_Parent]
GO
ALTER TABLE [dbo].[RESEARCH_PAPER]  WITH CHECK ADD  CONSTRAINT [FK_PAPER_Field] FOREIGN KEY([FieldID])
REFERENCES [dbo].[RESEARCH_FIELD] ([FieldID])
GO
ALTER TABLE [dbo].[RESEARCH_PAPER] CHECK CONSTRAINT [FK_PAPER_Field]
GO
ALTER TABLE [dbo].[RESEARCH_PAPER]  WITH CHECK ADD  CONSTRAINT [FK_PAPER_Journal] FOREIGN KEY([JournalID])
REFERENCES [dbo].[JOURNAL] ([JournalID])
GO
ALTER TABLE [dbo].[RESEARCH_PAPER] CHECK CONSTRAINT [FK_PAPER_Journal]
GO
ALTER TABLE [dbo].[RESEARCH_PAPER]  WITH CHECK ADD  CONSTRAINT [FK_PAPER_Source] FOREIGN KEY([SourceID])
REFERENCES [dbo].[API_SOURCE] ([SourceID])
GO
ALTER TABLE [dbo].[RESEARCH_PAPER] CHECK CONSTRAINT [FK_PAPER_Source]
GO
ALTER TABLE [dbo].[RESEARCH_TOPIC]  WITH CHECK ADD  CONSTRAINT [FK_TOPIC_Field] FOREIGN KEY([FieldID])
REFERENCES [dbo].[RESEARCH_FIELD] ([FieldID])
GO
ALTER TABLE [dbo].[RESEARCH_TOPIC] CHECK CONSTRAINT [FK_TOPIC_Field]
GO
ALTER TABLE [dbo].[SYNC_LOG]  WITH CHECK ADD  CONSTRAINT [FK_SYNC_Source] FOREIGN KEY([SourceID])
REFERENCES [dbo].[API_SOURCE] ([SourceID])
GO
ALTER TABLE [dbo].[SYNC_LOG] CHECK CONSTRAINT [FK_SYNC_Source]
GO
ALTER TABLE [dbo].[SYSTEM_CONFIG]  WITH CHECK ADD  CONSTRAINT [FK_CONFIG_UpdatedBy] FOREIGN KEY([UpdatedBy])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[SYSTEM_CONFIG] CHECK CONSTRAINT [FK_CONFIG_UpdatedBy]
GO
ALTER TABLE [dbo].[TOPIC_KEYWORD]  WITH CHECK ADD  CONSTRAINT [FK_TK_Keyword] FOREIGN KEY([KeywordID])
REFERENCES [dbo].[KEYWORD] ([KeywordID])
GO
ALTER TABLE [dbo].[TOPIC_KEYWORD] CHECK CONSTRAINT [FK_TK_Keyword]
GO
ALTER TABLE [dbo].[TOPIC_KEYWORD]  WITH CHECK ADD  CONSTRAINT [FK_TK_Topic] FOREIGN KEY([TopicID])
REFERENCES [dbo].[RESEARCH_TOPIC] ([TopicID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TOPIC_KEYWORD] CHECK CONSTRAINT [FK_TK_Topic]
GO
ALTER TABLE [dbo].[USER]  WITH CHECK ADD  CONSTRAINT [FK_USER_Role] FOREIGN KEY([RoleID])
REFERENCES [dbo].[ROLE] ([RoleID])
GO
ALTER TABLE [dbo].[USER] CHECK CONSTRAINT [FK_USER_Role]
GO
ALTER TABLE [dbo].[USER_SEARCH_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_USH_USER] FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_SEARCH_HISTORY] CHECK CONSTRAINT [FK_USH_USER]
GO
ALTER TABLE [dbo].[USER_SESSION]  WITH CHECK ADD  CONSTRAINT [FK_SESSION_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_SESSION] CHECK CONSTRAINT [FK_SESSION_User]
GO
ALTER TABLE [dbo].[USER_USAGE]  WITH CHECK ADD  CONSTRAINT [FK_USAGE_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USER_USAGE] CHECK CONSTRAINT [FK_USAGE_User]
GO
ALTER TABLE [dbo].[VERIFICATION_TOKEN]  WITH CHECK ADD  CONSTRAINT [FK_VT_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[VERIFICATION_TOKEN] CHECK CONSTRAINT [FK_VT_User]
GO
ALTER TABLE [dbo].[BOOKMARK]  WITH CHECK ADD  CONSTRAINT [CK_BOOKMARK_OneTarget] CHECK  (([PaperID] IS NOT NULL AND [KeywordID] IS NULL OR [PaperID] IS NULL AND [KeywordID] IS NOT NULL))
GO
ALTER TABLE [dbo].[BOOKMARK] CHECK CONSTRAINT [CK_BOOKMARK_OneTarget]
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET]  WITH CHECK ADD CHECK  (([WidgetType]='stat_card' OR [WidgetType]='pie_chart' OR [WidgetType]='bar_chart' OR [WidgetType]='line_chart'))
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET]  WITH CHECK ADD  CONSTRAINT [CK_DW_Position] CHECK  (([PositionX]>=(0) AND [PositionY]>=(0)))
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET] CHECK CONSTRAINT [CK_DW_Position]
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET]  WITH CHECK ADD  CONSTRAINT [CK_DW_Size] CHECK  (([Width]>=(1) AND [Height]>=(1)))
GO
ALTER TABLE [dbo].[DASHBOARD_WIDGET] CHECK CONSTRAINT [CK_DW_Size]
GO
ALTER TABLE [dbo].[FOLLOW]  WITH CHECK ADD  CONSTRAINT [CK_FOLLOW_OneTarget] CHECK  (([JournalID] IS NOT NULL AND [TopicID] IS NULL AND [KeywordID] IS NULL OR [JournalID] IS NULL AND [TopicID] IS NOT NULL AND [KeywordID] IS NULL OR [JournalID] IS NULL AND [TopicID] IS NULL AND [KeywordID] IS NOT NULL))
GO
ALTER TABLE [dbo].[FOLLOW] CHECK CONSTRAINT [CK_FOLLOW_OneTarget]
GO
ALTER TABLE [dbo].[JOURNAL]  WITH CHECK ADD CHECK  (([Quartile]='Q4' OR [Quartile]='Q3' OR [Quartile]='Q2' OR [Quartile]='Q1'))
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD CHECK  (([Type]='upgrade_prompt' OR [Type]='system' OR [Type]='trend_alert' OR [Type]='new_paper'))
GO
ALTER TABLE [dbo].[PAPER_AUTHOR]  WITH CHECK ADD  CONSTRAINT [CK_PA_AuthorOrder] CHECK  (([AuthorOrder]>=(1)))
GO
ALTER TABLE [dbo].[PAPER_AUTHOR] CHECK CONSTRAINT [CK_PA_AuthorOrder]
GO
ALTER TABLE [dbo].[PAPER_KEYWORD]  WITH CHECK ADD  CONSTRAINT [CK_PK_RelevanceScore] CHECK  (([RelevanceScore] IS NULL OR [RelevanceScore]>=(0) AND [RelevanceScore]<=(1)))
GO
ALTER TABLE [dbo].[PAPER_KEYWORD] CHECK CONSTRAINT [CK_PK_RelevanceScore]
GO
ALTER TABLE [dbo].[PDF_REQUEST]  WITH CHECK ADD  CONSTRAINT [CK_PDF_REQUEST_Status] CHECK  (([Status]='rejected' OR [Status]='fulfilled' OR [Status]='pending'))
GO
ALTER TABLE [dbo].[PDF_REQUEST] CHECK CONSTRAINT [CK_PDF_REQUEST_Status]
GO
ALTER TABLE [dbo].[PUBLICATION_TREND]  WITH CHECK ADD CHECK  (([PeriodType]='yearly' OR [PeriodType]='quarterly' OR [PeriodType]='monthly'))
GO
ALTER TABLE [dbo].[PUBLICATION_TREND]  WITH CHECK ADD CHECK  (([TrendTarget]='field' OR [TrendTarget]='journal' OR [TrendTarget]='topic' OR [TrendTarget]='keyword'))
GO
ALTER TABLE [dbo].[REPORT]  WITH CHECK ADD CHECK  (([Format]='csv' OR [Format]='pdf'))
GO
ALTER TABLE [dbo].[REPORT]  WITH CHECK ADD CHECK  (([Status]='failed' OR [Status]='completed' OR [Status]='generating'))
GO
ALTER TABLE [dbo].[REPORT]  WITH CHECK ADD  CONSTRAINT [CK_REPORT_Period] CHECK  (([PeriodEnd]>=[PeriodStart]))
GO
ALTER TABLE [dbo].[REPORT] CHECK CONSTRAINT [CK_REPORT_Period]
GO
ALTER TABLE [dbo].[RESEARCH_PAPER]  WITH CHECK ADD  CONSTRAINT [CK_PAPER_PubYear] CHECK  (([PubYear]>=(1900) AND [PubYear]<=(2100)))
GO
ALTER TABLE [dbo].[RESEARCH_PAPER] CHECK CONSTRAINT [CK_PAPER_PubYear]
GO
ALTER TABLE [dbo].[SYNC_LOG]  WITH CHECK ADD CHECK  (([Status]='failed' OR [Status]='completed' OR [Status]='running'))
GO
ALTER TABLE [dbo].[SYNC_LOG]  WITH CHECK ADD CHECK  (([SyncType]='incremental' OR [SyncType]='full'))
GO
ALTER TABLE [dbo].[TOPIC_KEYWORD]  WITH CHECK ADD  CONSTRAINT [CK_TK_Weight] CHECK  (([Weight]>=(0) AND [Weight]<=(1)))
GO
ALTER TABLE [dbo].[TOPIC_KEYWORD] CHECK CONSTRAINT [CK_TK_Weight]
GO
ALTER TABLE [dbo].[USER_USAGE]  WITH CHECK ADD  CONSTRAINT [CK_USAGE_Month] CHECK  (([UsageMonth] like '[0-9][0-9][0-9][0-9]-[0-1][0-9]'))
GO
ALTER TABLE [dbo].[USER_USAGE] CHECK CONSTRAINT [CK_USAGE_Month]
GO
ALTER TABLE [dbo].[VERIFICATION_TOKEN]  WITH CHECK ADD CHECK  (([TokenType]='PASSWORD_RESET' OR [TokenType]='EMAIL_VERIFICATION'))
GO
/****** Object:  StoredProcedure [dbo].[SP_CLEANUP_EXPIRED_SESSIONS]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- SP: Don dep session het han (chay dinh ky boi Scheduler)
CREATE   PROCEDURE [dbo].[SP_CLEANUP_EXPIRED_SESSIONS]
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM USER_SESSION WHERE ExpiresAt < SYSDATETIME();
    SELECT @@ROWCOUNT AS [DeletedSessions];
END;
GO
/****** Object:  StoredProcedure [dbo].[SP_CHECK_AND_INCREMENT_USAGE]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- ============================================================
--  STORED PROCEDURES
-- ============================================================

-- SP: Kiem tra va tang usage count cho Academic User
-- Tra ve 1 neu con trong gioi han, 0 neu da vuot
CREATE   PROCEDURE [dbo].[SP_CHECK_AND_INCREMENT_USAGE]
    @UserID     UNIQUEIDENTIFIER,
    @UsageType  NVARCHAR(20),       -- 'search' | 'view' | 'chart'
    @CanProceed BIT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Month      CHAR(7) = FORMAT(SYSDATETIME(), 'yyyy-MM');
    DECLARE @Current    INT     = 0;
    DECLARE @Limit      INT     = 999999;
    DECLARE @ConfigKey  NVARCHAR(100);

    SET @ConfigKey = CASE @UsageType
        WHEN 'search' THEN 'academic_monthly_search_limit'
        WHEN 'view'   THEN 'academic_monthly_view_limit'
        WHEN 'chart'  THEN 'academic_monthly_chart_limit'
        ELSE NULL
    END;

    IF @ConfigKey IS NULL
    BEGIN
        SET @CanProceed = 0;
        RETURN;
    END;

    -- Lay gioi han tu config
    SELECT @Limit = TRY_CAST(ConfigValue AS INT)
    FROM SYSTEM_CONFIG WHERE ConfigKey = @ConfigKey;

    -- Upsert record usage thang hien tai
    MERGE USER_USAGE AS target
    USING (SELECT @UserID AS UserID, @Month AS UsageMonth) AS src
    ON target.UserID = src.UserID AND target.UsageMonth = src.UsageMonth
    WHEN NOT MATCHED THEN
        INSERT (UserID, UsageMonth) VALUES (@UserID, @Month);

    -- Lay so hien tai
    SELECT @Current = CASE @UsageType
        WHEN 'search' THEN SearchCount
        WHEN 'view'   THEN ViewCount
        WHEN 'chart'  THEN ChartViewCount
    END
    FROM USER_USAGE
    WHERE UserID = @UserID AND UsageMonth = @Month;

    -- Kiem tra gioi han
    IF @Current >= @Limit
    BEGIN
        SET @CanProceed = 0;

        -- Tu dong tao thong bao upgrade_prompt neu chua co trong ngay hom nay
        IF NOT EXISTS (
            SELECT 1 FROM NOTIFICATION
            WHERE UserID = @UserID
              AND [Type] = 'upgrade_prompt'
              AND CAST(CreatedAt AS DATE) = CAST(SYSDATETIME() AS DATE)
        )
        INSERT INTO NOTIFICATION (UserID, [Type], Title, [Message])
        VALUES (
            @UserID,
            'upgrade_prompt',
            N'Ban da het luot su dung thang nay',
            N'Nang cap len Researcher de su dung khong gioi han va mo khoa tinh nang nang cao.'
        );
        RETURN;
    END;

    -- Tang count
    UPDATE USER_USAGE
    SET
        SearchCount    = CASE WHEN @UsageType = 'search' THEN SearchCount    + 1 ELSE SearchCount    END,
        ViewCount      = CASE WHEN @UsageType = 'view'   THEN ViewCount      + 1 ELSE ViewCount      END,
        ChartViewCount = CASE WHEN @UsageType = 'chart'  THEN ChartViewCount + 1 ELSE ChartViewCount END,
        LastUpdated    = SYSDATETIME()
    WHERE UserID = @UserID AND UsageMonth = @Month;

    -- Gui canh bao khi dat 80%
    IF (@Current + 1) >= (@Limit * 0.8)
       AND NOT EXISTS (
           SELECT 1 FROM NOTIFICATION
           WHERE UserID = @UserID
             AND [Type] = 'upgrade_prompt'
             AND CAST(CreatedAt AS DATE) = CAST(SYSDATETIME() AS DATE)
       )
    BEGIN
        INSERT INTO NOTIFICATION (UserID, [Type], Title, [Message])
        VALUES (
            @UserID,
            'upgrade_prompt',
            N'Ban sap het luot su dung (80%)',
            N'Con lai ' + CAST(@Limit - @Current - 1 AS NVARCHAR) +
            N' luot trong thang nay. Nang cap de dung khong gioi han.'
        );
    END;

    SET @CanProceed = 1;
END;
GO
/****** Object:  StoredProcedure [dbo].[SP_REFRESH_TOPIC_TRENDS]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- SP: Cap nhat TrendScore va IsTrending (chay sau moi sync)
CREATE   PROCEDURE [dbo].[SP_REFRESH_TOPIC_TRENDS]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Threshold DECIMAL(10,4) = 0.7;
    SELECT @Threshold = TRY_CAST(ConfigValue AS DECIMAL(10,4))
    FROM SYSTEM_CONFIG WHERE ConfigKey = 'trend_score_threshold';

    -- Cap nhat PaperCount
    UPDATE rt
    SET rt.PaperCount = (
        SELECT COUNT(DISTINCT pk.PaperID)
        FROM TOPIC_KEYWORD tk
        JOIN PAPER_KEYWORD pk ON tk.KeywordID = pk.KeywordID
        WHERE tk.TopicID = rt.TopicID
    ),
    rt.UpdatedAt = SYSDATETIME()
    FROM RESEARCH_TOPIC rt;

    -- Tinh TrendScore trung binh GrowthRate cac thang gan day
    UPDATE rt
    SET rt.TrendScore = ISNULL((
        SELECT AVG(pt.GrowthRate)
        FROM PUBLICATION_TREND pt
        WHERE pt.TrendTarget = 'topic'
          AND pt.TargetID    = rt.TopicID
          AND pt.PeriodType  = 'monthly'
          AND pt.GrowthRate  IS NOT NULL
    ), 0)
    FROM RESEARCH_TOPIC rt;

    -- Danh dau IsTrending
    UPDATE RESEARCH_TOPIC
    SET IsTrending = CASE WHEN TrendScore >= @Threshold THEN 1 ELSE 0 END;

    SELECT @@ROWCOUNT AS [UpdatedTopics];
END;
GO
/****** Object:  StoredProcedure [dbo].[SP_RESET_MONTHLY_USAGE]    Script Date: 7/3/2026 8:46:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- SP: Reset usage hang thang cho tat ca Academic User
-- Chay vao 00:00 ngay 1 hang thang
CREATE   PROCEDURE [dbo].[SP_RESET_MONTHLY_USAGE]
AS
BEGIN
    SET NOCOUNT ON;

    -- Khong xoa record cu, chi insert record moi cho thang moi
    -- Record cu giu lai de thong ke lich su su dung
    DECLARE @ThisMonth CHAR(7) = FORMAT(SYSDATETIME(), 'yyyy-MM');

    INSERT INTO USER_USAGE (UserID, UsageMonth, SearchCount, ViewCount, ChartViewCount)
    SELECT u.UserID, @ThisMonth, 0, 0, 0
    FROM [USER] u
    JOIN ROLE r ON u.RoleID = r.RoleID AND r.RoleName = 'academic_user'
    WHERE u.IsActive = 1
      AND NOT EXISTS (
          SELECT 1 FROM USER_USAGE
          WHERE UserID = u.UserID AND UsageMonth = @ThisMonth
      );

    SELECT @@ROWCOUNT AS [InitializedUsers];
END;
GO
USE [master]
GO
ALTER DATABASE [JournalTrendDB] SET  READ_WRITE 
GO
