spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:sqlserver://sql-journal-tracking.database.windows.net:1433;database=${DATABASE_NAME};user=${DATABASE_USERNAME}@sql-journal-tracking;password=${DATABASE_PASSWORD};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ===============================
# NEO4J CONFIG
# ===============================
spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}
# In log Cypher để dễ debug đồ án
logging.level.org.springframework.data.neo4j=INFO
server.forward-headers-strategy=framework
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# ===============================
# MAIL CONFIG (SMTP)
# ===============================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===============================
# APP CONFIG
# ===============================
app.frontend-url=${FRONTEND_URL:http://localhost:3000}
app.jwtSecret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwtExpirationInMs=${JWT_EXPIRATION:86400000}
app.reset-token-expiration-ms=${RESET_TOKEN_EXPIRATION:900000}