spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=${DATABASE_NAME};encrypt=true;trustServerCertificate=true
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true