-- ═══════════════════════════════════════════════════════════════
-- SCITRACK — Generated by OpenAlex Scraper v2.0
-- Generated at: 2026-06-29T06:18:24.400Z
-- Papers: 5
-- Query: machine unlearning
--
-- USAGE:
--   1. Open this file in SSMS / Azure Data Studio
--   2. Run against your SCITRACK database
--   3. Duplicates are skipped (DOI for papers, ISSN for journals,
--      NormalizedText for keywords, ExternalAuthorID for authors)
-- ═══════════════════════════════════════════════════════════════

BEGIN TRANSACTION;
GO

-- Ensure API_SOURCE exists
IF NOT EXISTS (SELECT 1 FROM API_SOURCE WHERE SourceName = 'OpenAlex')
BEGIN
    INSERT INTO API_SOURCE (SourceID, SourceName, BaseURL, IsActive, RateLimitRPM)
    VALUES (NEWID(), N'OpenAlex', N'https://api.openalex.org', 1, 100);
END
GO

DECLARE @SourceID UNIQUEIDENTIFIER = (SELECT SourceID FROM API_SOURCE WHERE SourceName = 'OpenAlex');
GO

-- ───────────────────────────────────────────────────────────────
-- [1/5] Dynamic capabilities: what are they?
-- OpenAlex: https://openalex.org/W2089402107
-- ───────────────────────────────────────────────────────────────

-- 1. Journal (upsert by ISSN)
DECLARE @JournalID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM JOURNAL WHERE ISSN = N'0143-2095')
    SET @JournalID = (SELECT JournalID FROM JOURNAL WHERE ISSN = N'0143-2095');
ELSE
BEGIN
    SET @JournalID = NEWID();
    INSERT INTO JOURNAL (JournalID, SourceID, JournalName, ISSN, Publisher, IsActive)
    VALUES (@JournalID, @SourceID, N'Strategic Management Journal', N'0143-2095', N'Wiley', 1);
END
GO

-- 2. Research Field (upsert by FieldName)
DECLARE @FieldID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM RESEARCH_FIELD WHERE FieldName = N'Business, Management and Accounting')
    SET @FieldID = (SELECT FieldID FROM RESEARCH_FIELD WHERE FieldName = N'Business, Management and Accounting');
ELSE
BEGIN
    SET @FieldID = NEWID();
    INSERT INTO RESEARCH_FIELD (FieldID, FieldName, IsTracked)
    VALUES (@FieldID, N'Business, Management and Accounting', 1);
END
GO

-- 3. Paper (skip if DOI exists)
DECLARE @PaperID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM RESEARCH_PAPER WHERE DOI = N'https://doi.org/10.1002/1097-0266(200010/11)21:10/11<1105::aid-smj133>3.0.co;2-e')
BEGIN
    SET @PaperID = (SELECT PaperID FROM RESEARCH_PAPER WHERE DOI = N'https://doi.org/10.1002/1097-0266(200010/11)21:10/11<1105::aid-smj133>3.0.co;2-e');
    PRINT 'W2089402107: DOI already exists, skipping paper INSERT (using existing PaperID: ' + CAST(@PaperID AS NVARCHAR(36)) + ')';
    -- Still ensure journal/field links are updated
    IF @JournalID IS NOT NULL
        UPDATE RESEARCH_PAPER SET JournalID = @JournalID WHERE PaperID = @PaperID AND JournalID IS NULL;
    IF @FieldID IS NOT NULL
        UPDATE RESEARCH_PAPER SET FieldID = @FieldID WHERE PaperID = @PaperID AND FieldID IS NULL;
END
ELSE
BEGIN
    SET @PaperID = NEWID();
    INSERT INTO RESEARCH_PAPER (PaperID, SourceID, JournalID, FieldID, Title, Abstract, DOI, PubDate, PubYear, CitationCount, IsOpenAccess)
    VALUES (
        @PaperID,
        @SourceID,
        @JournalID,
        @FieldID,
        N'Dynamic capabilities: what are they?',
        N'This paper focuses on dynamic capabilities and, more generally, the resource-based view of the firm. We argue that dynamic capabilities are a set of specific and identifiable processes such as product development, strategic decision making, and alliancing. They are neither vague nor tautological. Although dynamic capabilities are idiosyncratic in their details and path dependent in their emergence, they have significant commonalities across firms (popularly termed ‘best practice’). This suggests that they are more homogeneous, fungible, equifinal, and substitutable than is usually assumed. In moderately dynamic markets, dynamic capabilities resemble the traditional conception of routines. They are detailed, analytic, stable processes with predictable outcomes. In contrast, in high-velocity markets, they are simple, highly experiential and fragile processes with unpredictable outcomes. Finally, well-known learning mechanisms guide the evolution of dynamic capabilities. In moderately dynamic markets, the evolutionary emphasis is on variation. In high-velocity markets, it is on selection. At the level of RBV, we conclude that traditional RBV misidentifies the locus of long-term competitive advantage in dynamic markets, overemphasizes the strategic logic of leverage, and reaches a boundary condition in high-velocity markets. Copyright © 2000 John Wiley & Sons, Ltd.',
        N'https://doi.org/10.1002/1097-0266(200010/11)21:10/11<1105::aid-smj133>3.0.co;2-e',
        '2000-01-01',
        2000,
        14446,
        1
    );
END
GO

-- 4. Authors (2) + paper_author junction
-- Upsert by (SourceID, ExternalAuthorID); skip if already linked

--   Author: Kathleen M. Eisenhardt
DECLARE @AuthorID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5045613469')
    SET @AuthorID = (SELECT AuthorID FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5045613469');
ELSE
BEGIN
    SET @AuthorID = NEWID();
    INSERT INTO AUTHOR (AuthorID, SourceID, ExternalAuthorID, FullName, Affiliation, HIndex, TotalCitations)
    VALUES (@AuthorID, @SourceID, N'A5045613469', N'Kathleen M. Eisenhardt', N'Department of Management Science and Engineering, Stanford University, Stanford, California, U.S.A', 0, 0);
END

-- Link paper-author (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_AUTHOR WHERE PaperID = @PaperID AND AuthorID = @AuthorID)
BEGIN
    INSERT INTO PAPER_AUTHOR (PaperID, AuthorID, AuthorOrder, IsCorresponding)
    VALUES (@PaperID, @AuthorID, 1, 0);
END
GO

--   Author: Jeffrey A. Martin
DECLARE @AuthorID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5103803105')
    SET @AuthorID = (SELECT AuthorID FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5103803105');
ELSE
BEGIN
    SET @AuthorID = NEWID();
    INSERT INTO AUTHOR (AuthorID, SourceID, ExternalAuthorID, FullName, Affiliation, HIndex, TotalCitations)
    VALUES (@AuthorID, @SourceID, N'A5103803105', N'Jeffrey A. Martin', N'Department of Management Science and Engineering, Stanford University, Stanford, California, U.S.A', 0, 0);
END

-- Link paper-author (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_AUTHOR WHERE PaperID = @PaperID AND AuthorID = @AuthorID)
BEGIN
    INSERT INTO PAPER_AUTHOR (PaperID, AuthorID, AuthorOrder, IsCorresponding)
    VALUES (@PaperID, @AuthorID, 2, 0);
END
GO

-- 5. Keywords (10) + paper_keyword junction
-- Upsert by NormalizedText; skip if already linked

--   Keyword: Dynamic capabilities
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'dynamic capabilities')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'dynamic capabilities');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Dynamic capabilities', N'dynamic capabilities', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.9031);
END
GO

--   Keyword: Leverage (statistics)
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'leverage (statistics)')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'leverage (statistics)');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Leverage (statistics)', N'leverage (statistics)', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.6466);
END
GO

--   Keyword: Dynamic decision-making
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'dynamic decision-making')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'dynamic decision-making');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Dynamic decision-making', N'dynamic decision-making', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5041);
END
GO

--   Keyword: Resource (disambiguation)
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'resource (disambiguation)')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'resource (disambiguation)');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Resource (disambiguation)', N'resource (disambiguation)', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4502);
END
GO

--   Keyword: Industrial organization
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'industrial organization')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'industrial organization');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Industrial organization', N'industrial organization', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4437);
END
GO

--   Keyword: Microeconomics
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'microeconomics')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'microeconomics');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Microeconomics', N'microeconomics', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4420);
END
GO

--   Keyword: Set (abstract data type)
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'set (abstract data type)')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'set (abstract data type)');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Set (abstract data type)', N'set (abstract data type)', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4412);
END
GO

--   Keyword: Homogeneous
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'homogeneous')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'homogeneous');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Homogeneous', N'homogeneous', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4361);
END
GO

--   Keyword: Resource-based view
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'resource-based view')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'resource-based view');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Resource-based view', N'resource-based view', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4246);
END
GO

--   Keyword: Path dependence
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'path dependence')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'path dependence');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Path dependence', N'path dependence', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4170);
END
GO

-- ───────────────────────────────────────────────────────────────
-- [2/5] Situated Cognition and the Culture of Learning
-- OpenAlex: https://openalex.org/W2164599981
-- ───────────────────────────────────────────────────────────────

-- 1. Journal (upsert by ISSN)
DECLARE @JournalID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM JOURNAL WHERE ISSN = N'0013-189X')
    SET @JournalID = (SELECT JournalID FROM JOURNAL WHERE ISSN = N'0013-189X');
ELSE
BEGIN
    SET @JournalID = NEWID();
    INSERT INTO JOURNAL (JournalID, SourceID, JournalName, ISSN, Publisher, IsActive)
    VALUES (@JournalID, @SourceID, N'Educational Researcher', N'0013-189X', N'SAGE Publishing', 1);
END
GO

-- 2. Research Field (upsert by FieldName)
DECLARE @FieldID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM RESEARCH_FIELD WHERE FieldName = N'Social Sciences')
    SET @FieldID = (SELECT FieldID FROM RESEARCH_FIELD WHERE FieldName = N'Social Sciences');
ELSE
BEGIN
    SET @FieldID = NEWID();
    INSERT INTO RESEARCH_FIELD (FieldID, FieldName, IsTracked)
    VALUES (@FieldID, N'Social Sciences', 1);
END
GO

-- 3. Paper (skip if DOI exists)
DECLARE @PaperID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM RESEARCH_PAPER WHERE DOI = N'https://doi.org/10.3102/0013189x018001032')
BEGIN
    SET @PaperID = (SELECT PaperID FROM RESEARCH_PAPER WHERE DOI = N'https://doi.org/10.3102/0013189x018001032');
    PRINT 'W2164599981: DOI already exists, skipping paper INSERT (using existing PaperID: ' + CAST(@PaperID AS NVARCHAR(36)) + ')';
    -- Still ensure journal/field links are updated
    IF @JournalID IS NOT NULL
        UPDATE RESEARCH_PAPER SET JournalID = @JournalID WHERE PaperID = @PaperID AND JournalID IS NULL;
    IF @FieldID IS NOT NULL
        UPDATE RESEARCH_PAPER SET FieldID = @FieldID WHERE PaperID = @PaperID AND FieldID IS NULL;
END
ELSE
BEGIN
    SET @PaperID = NEWID();
    INSERT INTO RESEARCH_PAPER (PaperID, SourceID, JournalID, FieldID, Title, Abstract, DOI, PubDate, PubYear, CitationCount, IsOpenAccess)
    VALUES (
        @PaperID,
        @SourceID,
        @JournalID,
        @FieldID,
        N'Situated Cognition and the Culture of Learning',
        N'Many teaching practices implicitly assume that conceptual knowledge can be abstracted from the situations in which it is learned and used. This article argues that this assumption inevitably limits the effectiveness of such practices. Drawing on recent research into cognition as it is manifest in everyday activity, the authors argue that knowledge is situated, being in part a product of the activity, context, and culture in which it is developed and used. They discuss how this view of knowledge affects our understanding of learning, and they note that conventional schooling too often ignores the influence of school culture on what is learned in school. As an alternative to conventional practices, they propose cognitive apprenticeship (Collins, Brown, &amp; Newman, in press), which honors the situated nature of knowledge. They examine two examples of mathematics instruction that exhibit certain key features of this approach to teaching.',
        N'https://doi.org/10.3102/0013189x018001032',
        '1989-01-01',
        1989,
        12994,
        1
    );
END
GO

-- 4. Authors (3) + paper_author junction
-- Upsert by (SourceID, ExternalAuthorID); skip if already linked

--   Author: John Seely Brown
DECLARE @AuthorID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5111437337')
    SET @AuthorID = (SELECT AuthorID FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5111437337');
ELSE
BEGIN
    SET @AuthorID = NEWID();
    INSERT INTO AUTHOR (AuthorID, SourceID, ExternalAuthorID, FullName, Affiliation, HIndex, TotalCitations)
    VALUES (@AuthorID, @SourceID, N'A5111437337', N'John Seely Brown', N'Institute for Research on Learning, 2550 Hanover Street, Palo Alto, California 94304', 0, 0);
END

-- Link paper-author (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_AUTHOR WHERE PaperID = @PaperID AND AuthorID = @AuthorID)
BEGIN
    INSERT INTO PAPER_AUTHOR (PaperID, AuthorID, AuthorOrder, IsCorresponding)
    VALUES (@PaperID, @AuthorID, 1, 0);
END
GO

--   Author: Allan Collins
DECLARE @AuthorID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5108119978')
    SET @AuthorID = (SELECT AuthorID FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5108119978');
ELSE
BEGIN
    SET @AuthorID = NEWID();
    INSERT INTO AUTHOR (AuthorID, SourceID, ExternalAuthorID, FullName, Affiliation, HIndex, TotalCitations)
    VALUES (@AuthorID, @SourceID, N'A5108119978', N'Allan Collins', N'Institute for Research on Learning, 2550 Hanover Street, Palo Alto, California 94304', 0, 0);
END

-- Link paper-author (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_AUTHOR WHERE PaperID = @PaperID AND AuthorID = @AuthorID)
BEGIN
    INSERT INTO PAPER_AUTHOR (PaperID, AuthorID, AuthorOrder, IsCorresponding)
    VALUES (@PaperID, @AuthorID, 2, 0);
END
GO

--   Author: Paul Duguid
DECLARE @AuthorID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5106124458')
    SET @AuthorID = (SELECT AuthorID FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5106124458');
ELSE
BEGIN
    SET @AuthorID = NEWID();
    INSERT INTO AUTHOR (AuthorID, SourceID, ExternalAuthorID, FullName, Affiliation, HIndex, TotalCitations)
    VALUES (@AuthorID, @SourceID, N'A5106124458', N'Paul Duguid', N'BBN Inc, 10 Moulton Street, Cambridge, Massachusetts 02238', 0, 0);
END

-- Link paper-author (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_AUTHOR WHERE PaperID = @PaperID AND AuthorID = @AuthorID)
BEGIN
    INSERT INTO PAPER_AUTHOR (PaperID, AuthorID, AuthorOrder, IsCorresponding)
    VALUES (@PaperID, @AuthorID, 3, 0);
END
GO

-- 5. Keywords (10) + paper_keyword junction
-- Upsert by NormalizedText; skip if already linked

--   Keyword: Situated
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'situated')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'situated');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Situated', N'situated', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.9293);
END
GO

--   Keyword: Situated cognition
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'situated cognition')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'situated cognition');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Situated cognition', N'situated cognition', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.9042);
END
GO

--   Keyword: Cognitive apprenticeship
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'cognitive apprenticeship')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'cognitive apprenticeship');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Cognitive apprenticeship', N'cognitive apprenticeship', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.7705);
END
GO

--   Keyword: Situated learning
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'situated learning')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'situated learning');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Situated learning', N'situated learning', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.7376);
END
GO

--   Keyword: Context (archaeology)
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'context (archaeology)')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'context (archaeology)');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Context (archaeology)', N'context (archaeology)', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.6295);
END
GO

--   Keyword: Cognition
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'cognition')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'cognition');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Cognition', N'cognition', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5910);
END
GO

--   Keyword: Apprenticeship
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'apprenticeship')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'apprenticeship');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Apprenticeship', N'apprenticeship', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5182);
END
GO

--   Keyword: Product (mathematics)
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'product (mathematics)')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'product (mathematics)');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Product (mathematics)', N'product (mathematics)', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4722);
END
GO

--   Keyword: Epistemology
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'epistemology')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'epistemology');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Epistemology', N'epistemology', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4584);
END
GO

--   Keyword: Sociology
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'sociology')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'sociology');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Sociology', N'sociology', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4453);
END
GO

-- ───────────────────────────────────────────────────────────────
-- [3/5] Architectural Innovation: The Reconfiguration of Existing Product Technologies a
-- OpenAlex: https://openalex.org/W2095561982
-- ───────────────────────────────────────────────────────────────

-- 1. Journal (upsert by ISSN)
DECLARE @JournalID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM JOURNAL WHERE ISSN = N'0001-8392')
    SET @JournalID = (SELECT JournalID FROM JOURNAL WHERE ISSN = N'0001-8392');
ELSE
BEGIN
    SET @JournalID = NEWID();
    INSERT INTO JOURNAL (JournalID, SourceID, JournalName, ISSN, Publisher, IsActive)
    VALUES (@JournalID, @SourceID, N'Administrative Science Quarterly', N'0001-8392', N'SAGE Publishing', 1);
END
GO

-- 2. Research Field (upsert by FieldName)
DECLARE @FieldID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM RESEARCH_FIELD WHERE FieldName = N'Business, Management and Accounting')
    SET @FieldID = (SELECT FieldID FROM RESEARCH_FIELD WHERE FieldName = N'Business, Management and Accounting');
ELSE
BEGIN
    SET @FieldID = NEWID();
    INSERT INTO RESEARCH_FIELD (FieldID, FieldName, IsTracked)
    VALUES (@FieldID, N'Business, Management and Accounting', 1);
END
GO

-- 3. Paper (skip if DOI exists)
DECLARE @PaperID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM RESEARCH_PAPER WHERE DOI = N'https://doi.org/10.2307/2393549')
BEGIN
    SET @PaperID = (SELECT PaperID FROM RESEARCH_PAPER WHERE DOI = N'https://doi.org/10.2307/2393549');
    PRINT 'W2095561982: DOI already exists, skipping paper INSERT (using existing PaperID: ' + CAST(@PaperID AS NVARCHAR(36)) + ')';
    -- Still ensure journal/field links are updated
    IF @JournalID IS NOT NULL
        UPDATE RESEARCH_PAPER SET JournalID = @JournalID WHERE PaperID = @PaperID AND JournalID IS NULL;
    IF @FieldID IS NOT NULL
        UPDATE RESEARCH_PAPER SET FieldID = @FieldID WHERE PaperID = @PaperID AND FieldID IS NULL;
END
ELSE
BEGIN
    SET @PaperID = NEWID();
    INSERT INTO RESEARCH_PAPER (PaperID, SourceID, JournalID, FieldID, Title, Abstract, DOI, PubDate, PubYear, CitationCount, IsOpenAccess)
    VALUES (
        @PaperID,
        @SourceID,
        @JournalID,
        @FieldID,
        N'Architectural Innovation: The Reconfiguration of Existing Product Technologies and the Failure of Established Firms',
        N'Rebecca M. Henderson, Kim B. Clark, Architectural Innovation: The Reconfiguration of Existing Product Technologies and the Failure of Established Firms, Administrative Science Quarterly, Vol. 35, No. 1, Special Issue: Technology, Organizations, and Innovation (Mar., 1990), pp. 9-30',
        N'https://doi.org/10.2307/2393549',
        '1990-03-01',
        1990,
        8325,
        1
    );
END
GO

-- 4. Authors (2) + paper_author junction
-- Upsert by (SourceID, ExternalAuthorID); skip if already linked

--   Author: Rebecca Henderson
DECLARE @AuthorID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5102871257')
    SET @AuthorID = (SELECT AuthorID FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5102871257');
ELSE
BEGIN
    SET @AuthorID = NEWID();
    INSERT INTO AUTHOR (AuthorID, SourceID, ExternalAuthorID, FullName, Affiliation, HIndex, TotalCitations)
    VALUES (@AuthorID, @SourceID, N'A5102871257', N'Rebecca Henderson', N'Unknown', 0, 0);
END

-- Link paper-author (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_AUTHOR WHERE PaperID = @PaperID AND AuthorID = @AuthorID)
BEGIN
    INSERT INTO PAPER_AUTHOR (PaperID, AuthorID, AuthorOrder, IsCorresponding)
    VALUES (@PaperID, @AuthorID, 1, 0);
END
GO

--   Author: Kim B. Clark
DECLARE @AuthorID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5065484632')
    SET @AuthorID = (SELECT AuthorID FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5065484632');
ELSE
BEGIN
    SET @AuthorID = NEWID();
    INSERT INTO AUTHOR (AuthorID, SourceID, ExternalAuthorID, FullName, Affiliation, HIndex, TotalCitations)
    VALUES (@AuthorID, @SourceID, N'A5065484632', N'Kim B. Clark', N'Unknown', 0, 0);
END

-- Link paper-author (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_AUTHOR WHERE PaperID = @PaperID AND AuthorID = @AuthorID)
BEGIN
    INSERT INTO PAPER_AUTHOR (PaperID, AuthorID, AuthorOrder, IsCorresponding)
    VALUES (@PaperID, @AuthorID, 2, 0);
END
GO

-- 5. Keywords (10) + paper_keyword junction
-- Upsert by NormalizedText; skip if already linked

--   Keyword: Control reconfiguration
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'control reconfiguration')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'control reconfiguration');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Control reconfiguration', N'control reconfiguration', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.8048);
END
GO

--   Keyword: Business
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'business')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'business');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Business', N'business', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5244);
END
GO

--   Keyword: Product (mathematics)
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'product (mathematics)')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'product (mathematics)');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Product (mathematics)', N'product (mathematics)', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5034);
END
GO

--   Keyword: Industrial organization
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'industrial organization')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'industrial organization');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Industrial organization', N'industrial organization', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4033);
END
GO

--   Keyword: Process management
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'process management')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'process management');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Process management', N'process management', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.3848);
END
GO

--   Keyword: Knowledge management
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'knowledge management')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'knowledge management');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Knowledge management', N'knowledge management', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.3680);
END
GO

--   Keyword: Engineering
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'engineering')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'engineering');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Engineering', N'engineering', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.2394);
END
GO

--   Keyword: Computer science
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'computer science')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'computer science');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Computer science', N'computer science', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.2369);
END
GO

--   Keyword: Innovation and Knowledge Management
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'innovation and knowledge management')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'innovation and knowledge management');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Innovation and Knowledge Management', N'innovation and knowledge management', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.9976);
END
GO

--   Keyword: Business Strategy and Innovation
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'business strategy and innovation')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'business strategy and innovation');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Business Strategy and Innovation', N'business strategy and innovation', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.9897);
END
GO

-- ───────────────────────────────────────────────────────────────
-- [4/5] The Strength of Weak Learnability
-- OpenAlex: https://openalex.org/W2093717447
-- ───────────────────────────────────────────────────────────────

-- 1. Journal (upsert by ISSN)
DECLARE @JournalID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM JOURNAL WHERE ISSN = N'0885-6125')
    SET @JournalID = (SELECT JournalID FROM JOURNAL WHERE ISSN = N'0885-6125');
ELSE
BEGIN
    SET @JournalID = NEWID();
    INSERT INTO JOURNAL (JournalID, SourceID, JournalName, ISSN, Publisher, IsActive)
    VALUES (@JournalID, @SourceID, N'Machine Learning', N'0885-6125', N'Springer Science+Business Media', 1);
END
GO

-- 2. Research Field (upsert by FieldName)
DECLARE @FieldID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM RESEARCH_FIELD WHERE FieldName = N'Computer Science')
    SET @FieldID = (SELECT FieldID FROM RESEARCH_FIELD WHERE FieldName = N'Computer Science');
ELSE
BEGIN
    SET @FieldID = NEWID();
    INSERT INTO RESEARCH_FIELD (FieldID, FieldName, IsTracked)
    VALUES (@FieldID, N'Computer Science', 1);
END
GO

-- 3. Paper (skip if DOI exists)
DECLARE @PaperID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM RESEARCH_PAPER WHERE DOI = N'https://doi.org/10.1023/a:1022648800760')
BEGIN
    SET @PaperID = (SELECT PaperID FROM RESEARCH_PAPER WHERE DOI = N'https://doi.org/10.1023/a:1022648800760');
    PRINT 'W2093717447: DOI already exists, skipping paper INSERT (using existing PaperID: ' + CAST(@PaperID AS NVARCHAR(36)) + ')';
    -- Still ensure journal/field links are updated
    IF @JournalID IS NOT NULL
        UPDATE RESEARCH_PAPER SET JournalID = @JournalID WHERE PaperID = @PaperID AND JournalID IS NULL;
    IF @FieldID IS NOT NULL
        UPDATE RESEARCH_PAPER SET FieldID = @FieldID WHERE PaperID = @PaperID AND FieldID IS NULL;
END
ELSE
BEGIN
    SET @PaperID = NEWID();
    INSERT INTO RESEARCH_PAPER (PaperID, SourceID, JournalID, FieldID, Title, Abstract, DOI, PubDate, PubYear, CitationCount, IsOpenAccess)
    VALUES (
        @PaperID,
        @SourceID,
        @JournalID,
        @FieldID,
        N'The Strength of Weak Learnability',
        NULL,
        N'https://doi.org/10.1023/a:1022648800760',
        '1990-06-01',
        1990,
        3329,
        1
    );
END
GO

-- 4. Authors (1) + paper_author junction
-- Upsert by (SourceID, ExternalAuthorID); skip if already linked

--   Author: Robert E. Schapire
DECLARE @AuthorID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5084108666')
    SET @AuthorID = (SELECT AuthorID FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5084108666');
ELSE
BEGIN
    SET @AuthorID = NEWID();
    INSERT INTO AUTHOR (AuthorID, SourceID, ExternalAuthorID, FullName, Affiliation, HIndex, TotalCitations)
    VALUES (@AuthorID, @SourceID, N'A5084108666', N'Robert E. Schapire', N'MIT Laboratory for Computer Science, 545 Technology Square, Cambridge, MA, 02139', 0, 0);
END

-- Link paper-author (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_AUTHOR WHERE PaperID = @PaperID AND AuthorID = @AuthorID)
BEGIN
    INSERT INTO PAPER_AUTHOR (PaperID, AuthorID, AuthorOrder, IsCorresponding)
    VALUES (@PaperID, @AuthorID, 1, 0);
END
GO

-- 5. Keywords (10) + paper_keyword junction
-- Upsert by NormalizedText; skip if already linked

--   Keyword: Learnability
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'learnability')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'learnability');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Learnability', N'learnability', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.9458);
END
GO

--   Keyword: Concept class
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'concept class')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'concept class');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Concept class', N'concept class', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.6537);
END
GO

--   Keyword: Probably approximately correct learning
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'probably approximately correct learning')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'probably approximately correct learning');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Probably approximately correct learning', N'probably approximately correct learning', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.6092);
END
GO

--   Keyword: Class (philosophy)
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'class (philosophy)')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'class (philosophy)');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Class (philosophy)', N'class (philosophy)', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5866);
END
GO

--   Keyword: Computer science
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'computer science')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'computer science');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Computer science', N'computer science', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5422);
END
GO

--   Keyword: Set (abstract data type)
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'set (abstract data type)')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'set (abstract data type)');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Set (abstract data type)', N'set (abstract data type)', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5182);
END
GO

--   Keyword: Function (biology)
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'function (biology)')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'function (biology)');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Function (biology)', N'function (biology)', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5051);
END
GO

--   Keyword: Algorithm
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'algorithm')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'algorithm');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Algorithm', N'algorithm', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5015);
END
GO

--   Keyword: Fraction (chemistry)
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'fraction (chemistry)')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'fraction (chemistry)');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Fraction (chemistry)', N'fraction (chemistry)', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4825);
END
GO

--   Keyword: Mathematics
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'mathematics')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'mathematics');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Mathematics', N'mathematics', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4563);
END
GO

-- ───────────────────────────────────────────────────────────────
-- [5/5] Building dynamic capabilities for digital transformation: An ongoing process of 
-- OpenAlex: https://openalex.org/W2904649625
-- ───────────────────────────────────────────────────────────────

-- 1. Journal (upsert by ISSN)
DECLARE @JournalID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM JOURNAL WHERE ISSN = N'0024-6301')
    SET @JournalID = (SELECT JournalID FROM JOURNAL WHERE ISSN = N'0024-6301');
ELSE
BEGIN
    SET @JournalID = NEWID();
    INSERT INTO JOURNAL (JournalID, SourceID, JournalName, ISSN, Publisher, IsActive)
    VALUES (@JournalID, @SourceID, N'Long Range Planning', N'0024-6301', N'Elsevier BV', 1);
END
GO

-- 2. Research Field (upsert by FieldName)
DECLARE @FieldID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM RESEARCH_FIELD WHERE FieldName = N'Business, Management and Accounting')
    SET @FieldID = (SELECT FieldID FROM RESEARCH_FIELD WHERE FieldName = N'Business, Management and Accounting');
ELSE
BEGIN
    SET @FieldID = NEWID();
    INSERT INTO RESEARCH_FIELD (FieldID, FieldName, IsTracked)
    VALUES (@FieldID, N'Business, Management and Accounting', 1);
END
GO

-- 3. Paper (skip if DOI exists)
DECLARE @PaperID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM RESEARCH_PAPER WHERE DOI = N'https://doi.org/10.1016/j.lrp.2018.12.001')
BEGIN
    SET @PaperID = (SELECT PaperID FROM RESEARCH_PAPER WHERE DOI = N'https://doi.org/10.1016/j.lrp.2018.12.001');
    PRINT 'W2904649625: DOI already exists, skipping paper INSERT (using existing PaperID: ' + CAST(@PaperID AS NVARCHAR(36)) + ')';
    -- Still ensure journal/field links are updated
    IF @JournalID IS NOT NULL
        UPDATE RESEARCH_PAPER SET JournalID = @JournalID WHERE PaperID = @PaperID AND JournalID IS NULL;
    IF @FieldID IS NOT NULL
        UPDATE RESEARCH_PAPER SET FieldID = @FieldID WHERE PaperID = @PaperID AND FieldID IS NULL;
END
ELSE
BEGIN
    SET @PaperID = NEWID();
    INSERT INTO RESEARCH_PAPER (PaperID, SourceID, JournalID, FieldID, Title, Abstract, DOI, PubDate, PubYear, CitationCount, IsOpenAccess)
    VALUES (
        @PaperID,
        @SourceID,
        @JournalID,
        @FieldID,
        N'Building dynamic capabilities for digital transformation: An ongoing process of strategic renewal',
        NULL,
        N'https://doi.org/10.1016/j.lrp.2018.12.001',
        '2018-12-19',
        2018,
        2984,
        1
    );
END
GO

-- 4. Authors (2) + paper_author junction
-- Upsert by (SourceID, ExternalAuthorID); skip if already linked

--   Author: Karl Warner
DECLARE @AuthorID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5040950747')
    SET @AuthorID = (SELECT AuthorID FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5040950747');
ELSE
BEGIN
    SET @AuthorID = NEWID();
    INSERT INTO AUTHOR (AuthorID, SourceID, ExternalAuthorID, FullName, Affiliation, HIndex, TotalCitations)
    VALUES (@AuthorID, @SourceID, N'A5040950747', N'Karl Warner', N'Edinburgh Napier University, Room 2/44 Craiglockhart Campus, The Business School, Edinburgh, Scotland, EH14 1DJ, UK', 0, 0);
END

-- Link paper-author (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_AUTHOR WHERE PaperID = @PaperID AND AuthorID = @AuthorID)
BEGIN
    INSERT INTO PAPER_AUTHOR (PaperID, AuthorID, AuthorOrder, IsCorresponding)
    VALUES (@PaperID, @AuthorID, 1, 0);
END
GO

--   Author: Maximilian Wäger
DECLARE @AuthorID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5091723595')
    SET @AuthorID = (SELECT AuthorID FROM AUTHOR WHERE SourceID = @SourceID AND ExternalAuthorID = N'A5091723595');
ELSE
BEGIN
    SET @AuthorID = NEWID();
    INSERT INTO AUTHOR (AuthorID, SourceID, ExternalAuthorID, FullName, Affiliation, HIndex, TotalCitations)
    VALUES (@AuthorID, @SourceID, N'A5091723595', N'Maximilian Wäger', N'The Nunatak Group, Schackstrasse 3, 80539, München, Germany', 0, 0);
END

-- Link paper-author (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_AUTHOR WHERE PaperID = @PaperID AND AuthorID = @AuthorID)
BEGIN
    INSERT INTO PAPER_AUTHOR (PaperID, AuthorID, AuthorOrder, IsCorresponding)
    VALUES (@PaperID, @AuthorID, 2, 0);
END
GO

-- 5. Keywords (10) + paper_keyword junction
-- Upsert by NormalizedText; skip if already linked

--   Keyword: Digital transformation
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'digital transformation')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'digital transformation');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Digital transformation', N'digital transformation', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.7996);
END
GO

--   Keyword: Microfoundations
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'microfoundations')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'microfoundations');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Microfoundations', N'microfoundations', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.6594);
END
GO

--   Keyword: Process (computing)
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'process (computing)')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'process (computing)');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Process (computing)', N'process (computing)', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5519);
END
GO

--   Keyword: Dynamic capabilities
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'dynamic capabilities')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'dynamic capabilities');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Dynamic capabilities', N'dynamic capabilities', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5425);
END
GO

--   Keyword: Business model
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'business model')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'business model');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Business model', N'business model', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5425);
END
GO

--   Keyword: Process management
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'process management')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'process management');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Process management', N'process management', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.5148);
END
GO

--   Keyword: Contingency
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'contingency')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'contingency');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Contingency', N'contingency', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4986);
END
GO

--   Keyword: Context (archaeology)
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'context (archaeology)')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'context (archaeology)');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Context (archaeology)', N'context (archaeology)', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4792);
END
GO

--   Keyword: Knowledge management
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'knowledge management')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'knowledge management');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Knowledge management', N'knowledge management', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4681);
END
GO

--   Keyword: Computer science
DECLARE @KeywordID UNIQUEIDENTIFIER;
IF EXISTS (SELECT 1 FROM KEYWORD WHERE NormalizedText = N'computer science')
BEGIN
    SET @KeywordID = (SELECT KeywordID FROM KEYWORD WHERE NormalizedText = N'computer science');
    -- Increment paper count
    UPDATE KEYWORD SET PaperCount = PaperCount + 1 WHERE KeywordID = @KeywordID;
END
ELSE
BEGIN
    SET @KeywordID = NEWID();
    INSERT INTO KEYWORD (KeywordID, FieldID, KeywordText, NormalizedText, PaperCount)
    VALUES (@KeywordID, @FieldID, N'Computer science', N'computer science', 1);
END

-- Link paper-keyword (skip if already exists)
IF NOT EXISTS (SELECT 1 FROM PAPER_KEYWORD WHERE PaperID = @PaperID AND KeywordID = @KeywordID)
BEGIN
    INSERT INTO PAPER_KEYWORD (PaperID, KeywordID, RelevanceScore)
    VALUES (@PaperID, @KeywordID, 0.4678);
END
GO

-- ═══════════════════════════════════════════════════════════════
-- Cleanup: drop variables (optional, but clean)
-- ═══════════════════════════════════════════════════════════════
COMMIT TRANSACTION;
GO

PRINT '✅ Done! Processed 5 papers from OpenAlex.';
GO